services:
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mysql:
    container_name: mysql
    image: mysql:8.4.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: ripple
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9.3-jre-17
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_data_log:/datalog

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cassandra:
    container_name: cassandra
    image: cassandra:5.0.5
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: ripple_cluster
      CASSANDRA_USER: root
      CASSANDRA_PASSWORD: ripple
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE CLUSTER'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra-init:
    container_name: cassandra-init
    image: cassandra:5.0.5
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra-ddl/ripple.cql:/ripple.cql
    command: /bin/bash -c "
      echo 'Cassandra is healthy, starting initialization...' &&
      echo 'Loading cassandra keyspace...' &&
      cqlsh cassandra -f /ripple.cql &&
      echo 'Cassandra initialization completed successfully!'"
    restart: "no"

  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/var/lib/kafka/data

  # Ripple Application Services
  ripple-user-presence-server:
    container_name: ripple-user-presence-server
    build:
      context: .
      dockerfile: ripple-user-presence-server/Dockerfile
    ports:
      - "10101:10101"
    environment:
      SERVER_GRPC_PORT: 10101
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  ripple-snowflakeid-server:
    container_name: ripple-snowflakeid-server
    build:
      context: .
      dockerfile: ripple-snowflakeid-server/Dockerfile
    ports:
      - "10002:10002"
    environment:
      SERVER_GRPC_PORT: 10002
      ZOOKEEPER_ADDRESS: zookeeper:2181
      ZOOKEEPER_LOCK_PATH: /snowflakeid/lock
      ZOOKEEPER_IDS_PATH: /snowflakeid/workerIds
    depends_on:
      - zookeeper

  ripple-message-dispatcher:
    container_name: ripple-message-dispatcher
    build:
      context: .
      dockerfile: ripple-message-dispatcher/Dockerfile
    environment:
      RIPPLE_TOPIC_MESSAGE_CONSUMER_GROUP_ID: ripple-message-dispatcher-group
      RIPPLE_TOPIC_MESSAGE_CONSUMER_CLIENT_ID: ripple-message-dispatcher-client
      BROKER_TOPIC_MESSAGE: ripple-messages
      BROKER_SERVER: kafka:9092
      BROKER_TOPIC_PUSH: ripple-push-notifications
    depends_on:
      - kafka

  ripple-message-api-server:
    container_name: ripple-message-api-server
    build:
      context: .
      dockerfile: ripple-message-api-server/Dockerfile
    ports:
      - "10102:10102"
    environment:
      SERVER_GRPC_PORT: 10102
      RIPPLE_EXECUTOR_QUEUE_CAPACITY: 100
      BROKER_TOPIC_MESSAGE: ripple-messages
      BROKER_SERVER: kafka:9092
      CASSANDRA_CONTACT_POINTS.0: cassandra:9042
      CASSANDRA_KEYSPACE_NAME: ripple
      CASSANDRA_LOCAL_DATACENTER: datacenter1
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - cassandra
      - kafka

  ripple-message-gateway:
    container_name: ripple-message-gateway
    build:
      context: .
      dockerfile: ripple-message-gateway/Dockerfile
    ports:
      - "10004:10004"
      - "10100:10100"
    environment:
      WEBSOCKET_PORT: 10004
      WEBSOCKET_PATH: /ws
      SERVER_GRPC_PORT: 10100
      OAUTH2_JWK_SECRET: YjA4ZTY1MjAtM2I0OC00OGJiLTgyOTUtODY0Y2VlM2M4ZWJm
      RIPPLE_HEARTBEAT_IDLE_SECONDS: 60
    depends_on:
      - zookeeper

  ripple-push-server:
    container_name: ripple-push-server
    build:
      context: .
      dockerfile: ripple-push-server/Dockerfile
    environment:
      RIPPLE_TOPIC_PUSH_CONSUMER_GROUP_ID: ripple-push-server-group
      RIPPLE_TOPIC_PUSH_CONSUMER_CLIENT_ID: ripple-push-server-client
      BROKER_TOPIC_PUSH: ripple-push-notifications
      BROKER_SERVER: kafka:9092
      USER_PRESENCE_SERVICE_ADDRESS: ripple-user-presence-server:10101
      ZOOKEEPER_ADDRESS: zookeeper:2181
      ZOOKEEPER_MESSAGE_GATEWAY_DISCOVERY_PATH: /ripple/services/message-gateway
      PUSH_BATCH_QUEUE_SIZE: 1000
      PUSH_BATCH_WORKER_SIZE: 4
      PUSH_BATCH_MAX_SIZE: 50
      PUSH_BATCH_TIMEOUT_MS: 100
    depends_on:
      - kafka
      - zookeeper
      - ripple-user-presence-server
      - ripple-message-gateway

  ripple-authorization-server:
    container_name: ripple-authorization-server
    build:
      context: .
      dockerfile: ripple-authorization-server/Dockerfile
    ports:
      - "10001:10001"
    environment:
      SERVER_PORT: 10001
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ripple_im?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ripple
      OAUTH2_CLIENT_ID: ripple-im-desktop
      OAUTH2_CLIENT_SECRET: ripple
      OAUTH2_CLIENT_REDIRECT_URI: http://localhost:8000/callback
      OAUTH2_JWK_SECRET: YjA4ZTY1MjAtM2I0OC00OGJiLTgyOTUtODY0Y2VlM2M4ZWJm
      SNOWFLAKE_SERVER_HOST: ripple-snowflakeid-server
      SNOWFLAKE_SERVER_PORT: 10004
    depends_on:
      - mysql
      - ripple-snowflakeid-server

  ripple-upload-gateway:
    container_name: ripple-upload-gateway
    build:
      context: .
      dockerfile: ripple-upload-gateway/Dockerfile
    ports:
      - "10003:10003"
    environment:
      SERVER_PORT: 10003
      OAUTH2_JWK_SECRET: YjA4ZTY1MjAtM2I0OC00OGJiLTgyOTUtODY0Y2VlM2M4ZWJm
      CASSANDRA_CONTACT_POINTS: cassandra:9042
      CASSANDRA_KEYSPACE_NAME: ripple
      CASSANDRA_LOCAL_DATACENTER: datacenter1
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: ripple-avatars
    depends_on:
      - mysql
      - minio

  ripple-api-gateway:
    container_name: ripple-api-gateway
    build:
      context: .
      dockerfile: ripple-api-gateway/Dockerfile
    ports:
      - "10002:10002"
    environment:
      SERVER_PORT: 10002
      SPRING_APPLICATION_NAME: ripple-api-gateway
      OAUTH2_JWK_SECRET: YjA4ZTY1MjAtM2I0OC00OGJiLTgyOTUtODY0Y2VlM2M4ZWJm
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ripple_im
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ripple
      CASSANDRA_CONTACT_POINTS: cassandra:9042
      CASSANDRA_KEYSPACE_NAME: ripple
      MESSAGE_DISPATCHER_SERVER_ADDRESS: ripple-message-api-server:10102
    depends_on:
      - mysql
      - cassandra-init
      - ripple-message-api-server


volumes:
  minio_data:
  mysql_data:
  zookeeper_data:
  zookeeper_data_log:
  redis_data:
  cassandra_data:
  kafka_data: